### ISSUE TITLE
Allen Brain atlas reference files have moved to new URL

### ISSUE THREAD

**Issue by tomsing1** [satijalab/azimuth-references#1]
It seems that the reference `Mouse_M1_10xV3_Matrix.RDS` has moved and is no longer available from the URL listed in the Snakemake file:

https://github.com/satijalab/azimuth-references/blob/5f5255dac552d9ef86b872d37e212275cd0f2ae2/mouse_motorcortex/Snakefile#L14

**Comment by tomsing1** [comment]
I think the new location is: 

`http://data.nemoarchive.org/publication_release/2020_M1_study_analysis/Transcriptomics/sncell/10X/mouse/processed/counts/counts/M1/`

**Comment by andrewwbutler** [comment]
Thanks for bringing this up and sorry for the slow response. It looks like it's here now:

http://data.nemoarchive.org/publication_release/Lein_2020_M1_study_analysis/Transcriptomics/sncell/10X/mouse/processed/counts/counts/M1/

I've updated the URLs in the master branch to reflect this new location.
