### ISSUE TITLE
human_pancreas config.json

### ISSUE THREAD

**Issue by doncarlos999** [satijalab/azimuth-references#5]
Thanks for providing thorough scripts for recreating the reference files.

However I have noticed that the human_pancreas config.json located here: https://github.com/satijalab/azimuth-references/blob/08369eceaa460834b05b23f4987b05af1e0b0716/human_pancreas/reference/config.json is a copy of the human_lung config.json file. Would it be possible to get the correct human_pancreas config.json file uploaded here?

**Comment by andrewwbutler** [comment]
Thanks for pointing this out. Updated with the proper file now [here](https://github.com/satijalab/azimuth-references/blob/master/human_pancreas/reference/config.json).
